version: '3.9'

services:
  app:
    image: question_app
    build: .
    ports:
      - "8000:8000"
    command: bash -c "
      python -m venv venv;
      pip install --no-cache-dir -r requirements.txt;
      alembic upgrade head;
      uvicorn app.main:app
      --host app --port 8000 --reload
      "
    depends_on:
      - db

  db:
    image: pg
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: {}