"""initial

Revision ID: 38ac66c28445
Revises: 
Create Date: 2023-05-31 02:17:49.658253

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38ac66c28445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('question_text', sa.Text(), nullable=False),
                    sa.Column('answer_text', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('question_id'),
                    sa.UniqueConstraint('question_text')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
